server:
  http:
    addr: 0.0.0.0:20021
    timeout: 1s
  grpc:
    addr: 0.0.0.0:20022
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:mysql_TcKPjC@tcp(192.168.233.128:3306)/im_server?parseTime=True&loc=Local
  redis:
    addr: 192.168.233.128:6379
    username: default
    password: redis_jFFiD3
    read_timeout: 0.2s
    write_timeout: 0.2s
# 服务注册配置
registry:
  etcd:
    addr:
      - 192.168.233.128:2379
    key: auth