server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:mysql_TArH5E@tcp(154.8.197.123:3306)/im_server?parseTime=True&loc=Local
  redis:
    addr: 154.8.197.123:6379
    username: default
    password: redis_JQ4CAA
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  access_secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
  access_expire: 3600