// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 为某个枚举单独设置错误码
func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_NOT_FOUND.String() && e.Code == 401
}

// 为某个枚举单独设置错误码
func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsPasswordError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PASSWORD_ERROR.String() && e.Code == 401
}

func ErrorPasswordError(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_PASSWORD_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsAuthenticationFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AUTHENTICATION_FAILED.String() && e.Code == 401
}

func ErrorAuthenticationFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_AUTHENTICATION_FAILED.String(), fmt.Sprintf(format, args...))
}

func IsTokenEmpty(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TOKEN_EMPTY.String() && e.Code == 401
}

func ErrorTokenEmpty(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_TOKEN_EMPTY.String(), fmt.Sprintf(format, args...))
}

func IsParseTokenError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PARSE_TOKEN_ERROR.String() && e.Code == 401
}

func ErrorParseTokenError(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_PARSE_TOKEN_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsSetTokenError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SET_TOKEN_ERROR.String() && e.Code == 500
}

func ErrorSetTokenError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_SET_TOKEN_ERROR.String(), fmt.Sprintf(format, args...))
}
